In [1]:
# Colby Wirth
# COS 472 Assignment 1 
# September 24 2024

# We need to utilize many of the tools within the pandas library for data preprocessing
import pandas as pd

In [2]:
#Create a dataframe by parsing loan.csv with the pd.read_csv function

#The pd.read_csv function  parses comma separated values into columns, and each line into a row.

loan_df = pd.read_csv("loan.csv")

In [3]:
#The shape function gives the dimensions of the dataframe, columns x rows

loan_df.shape

(9592, 16)

In [4]:
#The columns field produces the labels separated by coommas on line 1 of the csv file

loan_df.columns

Index(['credit.policy', 'purpose', 'int.rate', 'installment', 'log.annual.inc',
       'dti', 'fico', 'days.with.cr.line', 'days.with.cr.line.1', 'revol.bal',
       'revol.util', 'history', 'inq.last.6mths', 'delinq.2yrs', 'pub.rec',
       'not.fully.paid'],
      dtype='object')

In [5]:
#The head() function produces a subset of the first five rows of the csv file.  This gives an overview of how the file is structured
loan_df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,days.with.cr.line.1,revol.bal,revol.util,history,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1.0,debt_consolidation,0.1189,829.10,11.350407,19.48,737.0,5639.958333,5639.958333,28854.0,52.1,NaN,0.0,0.0,0.0,0.0
1,1.0,debt_consolidation,0.1189,829.10,11.350407,19.48,737.0,5639.958333,5639.958333,28854.0,52.1,NaN,0.0,0.0,0.0,0.0
2,1.0,debt_consolidation,0.1189,829.10,11.350407,19.48,737.0,5639.958333,5639.958333,28854.0,52.1,NaN,0.0,0.0,0.0,0.0
3,1.0,credit_card,0.1071,228.22,11.082143,14.29,707.0,2760.000000,2760.000000,33623.0,76.7,NaN,0.0,0.0,0.0,0.0
4,1.0,debt_consolidation,NaN,366.86,10.373491,11.63,682.0,4710.000000,4710.000000,3511.0,25.6,NaN,1.0,0.0,0.0,0.0

In [6]:
#The info() function produces a range of all of the entries, their column labels with their respective datatypes and null counts.
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9592 entries, 0 to 9591
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   credit.policy        9591 non-null   float64
 1   purpose              9589 non-null   object
 2   int.rate             9588 non-null   float64
 3   installment          9588 non-null   float64
 4   log.annual.inc       9590 non-null   float64
 5   dti                  9591 non-null   float64
 6   fico                 9591 non-null   float64
 7   days.with.cr.line    9591 non-null   float64
 8   days.with.cr.line.1  9591 non-null   float64
 9   revol.bal            9590 non-null   float64
 10  revol.util           9591 non-null   float64
 11  history              0 non-null      float64
 12  inq.last.6mths       9591 non-null   float64
 13  delinq.2yrs          9591 non-null   float64
 14  pub.rec              9591 non-null   float64
 15  not.fully.paid       9589 non-null   float64
dtypes: float64(15), object(1)
memory usage: 1.2+ MB

In [7]:
#The describe() function gives useful statistical data regarding each attribute in the columns.

#The 'T' transposes the dataframe as you would a matrix.

loan_df.describe().T

,count,mean,std,min,25%,50%,75%,max
credit.policy,9591.0,0.805234,0.396041,0.000000,1.000000,1.000000,1.000000,1.000000e+00
int.rate,9588.0,0.122613,0.026847,0.060000,0.103900,0.122100,0.140700,2.164000e-01
installment,9588.0,319.301064,207.110666,15.670000,163.770000,268.950000,433.145000,9.401400e+02
log.annual.inc,9590.0,10.931806,0.614779,7.547502,10.558414,10.927987,11.289832,1.452835e+01
dti,9591.0,12.604236,6.882582,0.000000,7.200000,12.670000,17.950000,2.996000e+01
fico,9591.0,710.888541,37.973225,612.000000,682.000000,707.000000,737.000000,8.270000e+02
days.with.cr.line,9591.0,4565.605907,2503.435231,178.958333,2820.000000,4139.958333,5730.000000,1.763996e+04
days.with.cr.line.1,9591.0,4565.605907,2503.435231,178.958333,2820.000000,4139.958333,5730.000000,1.763996e+04
revol.bal,9590.0,16901.412513,33738.274235,0.000000,3188.250000,8560.500000,18239.250000,1.207359e+06
revol.util,9591.0,46.765142,29.011697,0.000000,22.600000,46.200000,70.900000,1.190000e+02
history,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
inq.last.6mths,9591.0,1.575018,2.199530,0.000000,0.000000,1.000000,2.000000,3.300000e+01
delinq.2yrs,9591.0,0.163487,0.545878,0.000000,0.000000,0.000000,0.000000,1.300000e+01
pub.rec,9591.0,0.062037,0.261959,0.000000,0.000000,0.000000,0.000000,5.000000e+00
not.fully.paid,9589.0,0.159871,0.366505,0.000000,0.000000,0.000000,0.000000,1.000000e+00

In [8]:
#The drop function removes the indicated columns,
#  axis 1 refers to columns (axis 0 would refer to rows)
# 'inplace' refers to chaning the df referenced in memory - false would return a new df

#We are dropping the duplicate attribute, and the empty atrribute present in the df specifically here

loan_df.drop(['days.with.cr.line.1', 'history'], axis=1, inplace=True)

In [9]:
#Verify the change have beenn made
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9592 entries, 0 to 9591
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   credit.policy      9591 non-null   float64
 1   purpose            9589 non-null   object
 2   int.rate           9588 non-null   float64
 3   installment        9588 non-null   float64
 4   log.annual.inc     9590 non-null   float64
 5   dti                9591 non-null   float64
 6   fico               9591 non-null   float64
 7   days.with.cr.line  9591 non-null   float64
 8   revol.bal          9590 non-null   float64
 9   revol.util         9591 non-null   float64
 10  inq.last.6mths     9591 non-null   float64
 11  delinq.2yrs        9591 non-null   float64
 12  pub.rec            9591 non-null   float64
 13  not.fully.paid     9589 non-null   float64
dtypes: float64(13), object(1)
memory usage: 1.0+ MB

In [10]:
#Now we take count of how many dupliacted rows exist in the df

loan_df.duplicated().sum()

13

In [11]:
#remove the duplicated rows

loan_df = loan_df.drop_duplicates()

In [12]:
#Verify the 13 duplicated rows have been dropped
loan_df.shape

(9579, 14)

In [13]:
#Now we must handle null values

loan_df.isnull().sum()

credit.policy        1
purpose              3
int.rate             4
installment          4
log.annual.inc       2
dti                  1
fico                 1
days.with.cr.line    1
revol.bal            2
revol.util           1
inq.last.6mths       1
delinq.2yrs          1
pub.rec              1
not.fully.paid       3
dtype: int64

In [14]:
#Identify nominal values for the purpose attribute
loan_df['purpose'].value_counts()

purpose
debt_consolidation    3956
all_other             2330
credit_card           1262
home_improvement       629
small_business         619
major_purchase         437
educational            343
Name: count, dtype: int64

In [15]:
#Use a standard value to fill nan values for purpose attriburte
loan_df['purpose'].fillna('debt_consolidation',inplace=True)

/var/folders/xk/fhgbj8qj60n54b05mpfnck0w0000gn/T/ipykernel_66672/948049042.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  loan_df['purpose'].fillna('debt_consolidation',inplace=True)

In [16]:
#verify that the nan values for purpose have been filled
loan_df.isnull().sum()

credit.policy        1
purpose              0
int.rate             4
installment          4
log.annual.inc       2
dti                  1
fico                 1
days.with.cr.line    1
revol.bal            2
revol.util           1
inq.last.6mths       1
delinq.2yrs          1
pub.rec              1
not.fully.paid       3
dtype: int64

In [17]:
#remvoe all rows with nan values
df_cleaned = loan_df.dropna()

In [18]:
#verify no nan values remain
df_cleaned.isnull().sum()

credit.policy        0
purpose              0
int.rate             0
installment          0
log.annual.inc       0
dti                  0
fico                 0
days.with.cr.line    0
revol.bal            0
revol.util           0
inq.last.6mths       0
delinq.2yrs          0
pub.rec              0
not.fully.paid       0
dtype: int64

In [19]:
#Verify info
df_cleaned.shape

(9568, 14)

In [20]:
#View info of cleaned df
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9568 entries, 0 to 9591
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   credit.policy      9568 non-null   float64
 1   purpose            9568 non-null   object
 2   int.rate           9568 non-null   float64
 3   installment        9568 non-null   float64
 4   log.annual.inc     9568 non-null   float64
 5   dti                9568 non-null   float64
 6   fico               9568 non-null   float64
 7   days.with.cr.line  9568 non-null   float64
 8   revol.bal          9568 non-null   float64
 9   revol.util         9568 non-null   float64
 10  inq.last.6mths     9568 non-null   float64
 11  delinq.2yrs        9568 non-null   float64
 12  pub.rec            9568 non-null   float64
 13  not.fully.paid     9568 non-null   float64
dtypes: float64(13), object(1)
memory usage: 1.1+ MB

In [21]:
df_cleaned.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1.0,debt_consolidation,0.1189,829.10,11.350407,19.48,737.0,5639.958333,28854.0,52.1,0.0,0.0,0.0,0.0
3,1.0,credit_card,0.1071,228.22,11.082143,14.29,707.0,2760.000000,33623.0,76.7,0.0,0.0,0.0,0.0
5,1.0,debt_consolidation,0.1008,162.34,11.350407,8.10,712.0,2699.958333,33667.0,73.2,1.0,0.0,0.0,0.0
6,1.0,credit_card,0.1426,102.92,11.299732,14.97,667.0,4066.000000,4740.0,39.5,0.0,1.0,0.0,0.0
7,1.0,credit_card,0.0788,125.13,11.904968,16.98,727.0,6120.041667,50807.0,51.0,0.0,0.0,0.0,0.0

In [22]:
#Now we must change the object data listed under purpose into 1s and 0s, represented Boolean values

# List of columns to fill missing values with their mean
columns = ['credit.policy', 'int.rate', 'installment', 'log.annual.inc', 
           'dti', 'fico', 'days.with.cr.line', 'revol.bal', 'revol.util', 
           'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid']

# Iterate over the columns and fill missing values with the mean
for col in columns:
    loan_df[col] = loan_df[col].fillna(loan_df[col].mean())

In [23]:
#Create a temporary df to house the new attributes

df_enconde = pd.get_dummies(loan_df, columns=['purpose'], dtype=int)

In [59]:
# adjust order, put the label column 'not fully paid' to last

#pop target column
col= df_enconde.pop('not.fully.paid')

#add it back to df
df_enconde['not.fully.paid'] = col

In [24]:
#verify data has been updated correctly with new attributes
df_enconde

,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,purpose_all_other,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_major_purchase,purpose_small_business
0,1.0,0.11890,829.10,11.350407,19.48,737.0,5639.958333,28854.0,52.1,0.0,0.0,0.0,0.0,0,0,1,0,0,0,0
3,1.0,0.10710,228.22,11.082143,14.29,707.0,2760.000000,33623.0,76.7,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0
4,1.0,0.12264,366.86,10.373491,11.63,682.0,4710.000000,3511.0,25.6,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0
5,1.0,0.10080,162.34,11.350407,8.10,712.0,2699.958333,33667.0,73.2,1.0,0.0,0.0,0.0,0,0,1,0,0,0,0
6,1.0,0.14260,102.92,11.299732,14.97,667.0,4066.000000,4740.0,39.5,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9587,0.0,0.14610,344.76,12.180755,10.39,672.0,10474.000000,215372.0,82.1,2.0,0.0,0.0,1.0,1,0,0,0,0,0,0
9588,0.0,0.12530,257.70,11.141862,0.21,722.0,4380.000000,184.0,1.1,5.0,0.0,0.0,1.0,1,0,0,0,0,0,0
9589,0.0,0.10710,97.81,10.596635,13.09,687.0,3450.041667,10036.0,82.9,8.0,0.0,0.0,1.0,0,0,1,0,0,0,0
9590,0.0,0.16000,351.58,10.819778,19.18,692.0,1800.000000,0.0,3.2,5.0,0.0,0.0,1.0,0,0,0,0,1,0,0
9591,0.0,0.13920,853.43,11.264464,16.28,732.0,4740.000000,37879.0,57.0,6.0,0.0,0.0,1.0,0,0,1,0,0,0,0